/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pharbers.kafka.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class JobResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5174896824032002012L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JobResponse\",\"namespace\":\"com.pharbers.kafka.schema\",\"fields\":[{\"name\":\"jobType\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence jobType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JobResponse() {}

  /**
   * All-args constructor.
   * @param jobType The new value for jobType
   */
  public JobResponse(java.lang.CharSequence jobType) {
    this.jobType = jobType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jobType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jobType = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'jobType' field.
   * @return The value of the 'jobType' field.
   */
  public java.lang.CharSequence getJobType() {
    return jobType;
  }

  /**
   * Sets the value of the 'jobType' field.
   * @param value the value to set.
   */
  public void setJobType(java.lang.CharSequence value) {
    this.jobType = value;
  }

  /**
   * Creates a new JobResponse RecordBuilder.
   * @return A new JobResponse RecordBuilder
   */
  public static com.pharbers.kafka.schema.JobResponse.Builder newBuilder() {
    return new com.pharbers.kafka.schema.JobResponse.Builder();
  }

  /**
   * Creates a new JobResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JobResponse RecordBuilder
   */
  public static com.pharbers.kafka.schema.JobResponse.Builder newBuilder(com.pharbers.kafka.schema.JobResponse.Builder other) {
    return new com.pharbers.kafka.schema.JobResponse.Builder(other);
  }

  /**
   * Creates a new JobResponse RecordBuilder by copying an existing JobResponse instance.
   * @param other The existing instance to copy.
   * @return A new JobResponse RecordBuilder
   */
  public static com.pharbers.kafka.schema.JobResponse.Builder newBuilder(com.pharbers.kafka.schema.JobResponse other) {
    return new com.pharbers.kafka.schema.JobResponse.Builder(other);
  }

  /**
   * RecordBuilder for JobResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JobResponse>
    implements org.apache.avro.data.RecordBuilder<JobResponse> {

    private java.lang.CharSequence jobType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pharbers.kafka.schema.JobResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.jobType)) {
        this.jobType = data().deepCopy(fields()[0].schema(), other.jobType);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing JobResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pharbers.kafka.schema.JobResponse other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.jobType)) {
        this.jobType = data().deepCopy(fields()[0].schema(), other.jobType);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'jobType' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobType() {
      return jobType;
    }

    /**
      * Sets the value of the 'jobType' field.
      * @param value The value of 'jobType'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.JobResponse.Builder setJobType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.jobType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'jobType' field has been set.
      * @return True if the 'jobType' field has been set, false otherwise.
      */
    public boolean hasJobType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'jobType' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.JobResponse.Builder clearJobType() {
      jobType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public JobResponse build() {
      try {
        JobResponse record = new JobResponse();
        record.jobType = fieldSetFlags()[0] ? this.jobType : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
